/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoconexion;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leoth
 */
public class MenuProyectos extends javax.swing.JFrame {

    /**
     * Creates new form MenuProyectos
     */
    public MenuProyectos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Consulta1BTN = new javax.swing.JButton();
        Consulta2BTN = new javax.swing.JButton();
        ConsultaBTN = new javax.swing.JButton();
        Consulta4BTN = new javax.swing.JButton();
        Consulta5BTN = new javax.swing.JButton();
        VolverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 214, 155));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Proyectos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        Consulta1BTN.setBackground(new java.awt.Color(255, 255, 255));
        Consulta1BTN.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Consulta1BTN.setText("Consulta 1");
        Consulta1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta1BTNActionPerformed(evt);
            }
        });

        Consulta2BTN.setBackground(new java.awt.Color(255, 255, 255));
        Consulta2BTN.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Consulta2BTN.setText("Consulta 2");
        Consulta2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta2BTNActionPerformed(evt);
            }
        });

        ConsultaBTN.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaBTN.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ConsultaBTN.setText("Consulta 3");
        ConsultaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaBTNActionPerformed(evt);
            }
        });

        Consulta4BTN.setBackground(new java.awt.Color(255, 255, 255));
        Consulta4BTN.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Consulta4BTN.setText("Consulta 4");
        Consulta4BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta4BTNActionPerformed(evt);
            }
        });

        Consulta5BTN.setBackground(new java.awt.Color(255, 255, 255));
        Consulta5BTN.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Consulta5BTN.setText("Consulta 5");

        VolverBTN.setBackground(new java.awt.Color(255, 0, 0));
        VolverBTN.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        VolverBTN.setForeground(new java.awt.Color(255, 255, 255));
        VolverBTN.setText("Volver");
        VolverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Consulta5BTN)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ConsultaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Consulta2BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Consulta1BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Consulta4BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(VolverBTN)
                        .addGap(359, 359, 359))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Consulta1BTN)
                .addGap(56, 56, 56)
                .addComponent(Consulta2BTN)
                .addGap(55, 55, 55)
                .addComponent(ConsultaBTN)
                .addGap(59, 59, 59)
                .addComponent(Consulta4BTN)
                .addGap(55, 55, 55)
                .addComponent(Consulta5BTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(VolverBTN)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    Conexion con = new Conexion();



    private void VolverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBTNActionPerformed
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            menu.pack();
            menu.setLocationRelativeTo(null);
            menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_VolverBTNActionPerformed

    private void Consulta1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta1BTNActionPerformed
       con.ConectarmeV2();

       Consulta1_Proyectos c1_pro = new Consulta1_Proyectos();
       c1_pro.setVisible(true);
       c1_pro.pack();
       c1_pro.setLocationRelativeTo(null);
       c1_pro.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();


       PreparedStatement pst;
       ResultSet rst = null;

    String consulta = "SELECT p.estadoproyecto , Count(*) as cantidad\n" +
       "From public.proyectosoftware p \n" +
       "Group by p.estadoproyecto";



     DefaultTableModel dftable = (DefaultTableModel) c1_pro.TablaConsulta1_Proyectos.getModel();

           int cantfila = c1_pro.TablaConsulta1_Proyectos.getRowCount();
           for(int i = cantfila - 1; i>=0; i--){
               dftable.removeRow(i);
           }


    try{
       pst = con.conexion.prepareStatement(consulta);
       rst = pst.executeQuery();

       while(rst.next()){

           String EstadoProyecto = rst.getString("estadoproyecto");
           int Cantidad = rst.getInt("cantidad");

           Object[] obj ={EstadoProyecto, Cantidad};
           dftable.addRow(obj);
       }

    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
    }



    }//GEN-LAST:event_Consulta1BTNActionPerformed

    private void Consulta2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta2BTNActionPerformed
        con.ConectarmeV2();

       Consulta2_Proyectos c2_pro = new Consulta2_Proyectos();
       c2_pro.setVisible(true);
       c2_pro.pack();
       c2_pro.setLocationRelativeTo(null);
       c2_pro.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();


       PreparedStatement pst;
       ResultSet rst = null;

    String consulta = "SELECT *\n" +
    "From public.proyectosoftware ";



     DefaultTableModel dftable = (DefaultTableModel) c2_pro.TablaConsulta2_Proyectos.getModel();

           int cantfila = c2_pro.TablaConsulta2_Proyectos.getRowCount();
           for(int i = cantfila - 1; i>=0; i--){
               dftable.removeRow(i);
           }


    try{
       pst = con.conexion.prepareStatement(consulta);
       rst = pst.executeQuery();

       while(rst.next()){

           String EstadoProyecto = rst.getString("estadoproyecto");
           String Pseunombre = rst.getString("pseunombre");
           String UrlTrello = rst.getString("urltrello");
           String FechaCreacion = rst.getString("fechacreacion");
           String FechaAsignacion = rst.getString("fechacreacion");
           String UrlGithub = rst.getString("urlgithub");
           String EquipoTrbajo = rst.getString("equipotrabajo_idequipo");
           int IdProyecto = rst.getInt("proyectosoftware_id");


           Object[] obj ={EstadoProyecto, Pseunombre, UrlTrello, FechaCreacion, FechaAsignacion, UrlGithub, EquipoTrbajo, IdProyecto};
           dftable.addRow(obj);
       }

    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
    }





    }//GEN-LAST:event_Consulta2BTNActionPerformed

    private void ConsultaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaBTNActionPerformed
        Consulta3_Proyectos c3_pro = new Consulta3_Proyectos();
        c3_pro.setVisible(true);
        c3_pro.pack();
        c3_pro.setLocationRelativeTo(null);
        c3_pro.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ConsultaBTNActionPerformed

    private void Consulta4BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta4BTNActionPerformed
        Consulta4_Proyectos c4_pro = new Consulta4_Proyectos();
        c4_pro.setVisible(true);
        c4_pro.pack();
        c4_pro.setLocationRelativeTo(null);
        c4_pro.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_Consulta4BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consulta1BTN;
    private javax.swing.JButton Consulta2BTN;
    private javax.swing.JButton Consulta4BTN;
    private javax.swing.JButton Consulta5BTN;
    private javax.swing.JButton ConsultaBTN;
    private javax.swing.JButton VolverBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
